### ISSUE TITLE
Название переменной не отображает назначения переменной

### ISSUE THREAD

**Issue by coursar** [dashafromrussia/homework4.1#4]
https://github.com/dashafromrussia/homework4.1/blob/3ddc486244f9da6d1ebd0573e6df841c13e4e7ba/src/js/lib.js#L2

**Comment by dashafromrussia** [comment]
Travis 36687f756e545a78ead5c18928cc341c54c8b960

**Comment by dashafromrussia** [comment]
@coursar  codecov 8670f2ea190b1eea9e0afc60c3440a4726880b76
